In [1]:
#To import necessary libraries
import pandas as pd

In [2]:
#To read the file
df = pd.read_csv(r"C:\Users\ritik\Downloads\customer_shopping_behavior.csv")

In [3]:
#To know how our data looks like
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
#To know the datatypes
df.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [5]:
#Statistical Analysis
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

In [6]:
#To check the null values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df['Review Rating'].fillna(df.groupby('Category')['Review Rating'].transform('median'))

In [8]:
#To check if any null values present
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
#To create 'age_group' column
labels=['young','middle-aged','adult','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [11]:
#To check if age_group is created or not
df[['age','age_group']]

      age    age_group
0      55        adult
1      19        young
2      50        adult
3      21        young
4      45        adult
...   ...          ...
3895   40  middle-aged
3896   52        adult
3897   46        adult
3898   44  middle-aged
3899   52        adult

[3900 rows x 2 columns]

In [12]:
#To check how many unique values are present
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [13]:
#To create column purchase frequency days
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 months':90
}
df['purchase_frequency']=df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
#To check if column is created
df[['purchase_frequency','frequency_of_purchases']]

      purchase_frequency frequency_of_purchases
0                   14.0            Fortnightly
1                   14.0            Fortnightly
2                    7.0                 Weekly
3                    7.0                 Weekly
4                  365.0               Annually
...                  ...                    ...
3895                 7.0                 Weekly
3896                14.0              Bi-Weekly
3897                90.0              Quarterly
3898                 7.0                 Weekly
3899                90.0              Quarterly

[3900 rows x 2 columns]

In [15]:
df[['discount_applied','promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [16]:
#To check if both these columns carry same values
df['discount_applied'].equals(df['promo_code_used'])

True

In [17]:
#Since both the columns carry same values, we'll drop the column 'promo_case_used'
df.drop('promo_code_used',axis=1,inplace=True)

In [18]:
import sys
print(sys.executable)

c:\Users\ritik\AppData\Local\Programs\Python\Python313\python.exe

In [19]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\ritik\appdata\local\programs\python\python313\lib\site-packages (2.0.46)
Requirement already satisfied: pymysql in c:\users\ritik\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\ritik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ritik\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
from sqlalchemy import create_engine # pyright: ignore[reportMissingImports]

engine = create_engine(
    "mysql+pymysql://root:Vanilla@123@localhost:3306/customer_behaviour_analysis"
)

In [21]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Vanilla%40123@localhost:3306/customer_behaviour_analysis"
)

In [22]:
table_name = "customer"

df.to_sql(
    name=table_name,
    con=engine,            # ✅ correct keyword
    if_exists="replace",   # or "append"
    index=False
)

print("Data successfully loaded ✅")

Data successfully loaded ✅